version: '2'

services:

### Web Container ###########################
    web:
        build:
            context: .docker/web
        depends_on:
            - mysql
        ports:
            - "80:80"
        expose:
            - 80
        volumes:
            - .:/www

### MySQL Container #########################################
    mysql:
        build:
            context: .docker/mysql
        environment:
            - MYSQL_DATABASE=homestead
            - MYSQL_USER=homestead
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=root
        expose:
            - 3306
